services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_shop
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db

  app:
    build: .
    container_name: spring_app_container
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DOCKER_COMPOSE_ENABLED=false
      - SPRING_DATA_MONGODB_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/${DB_NAME}?authSource=admin

volumes:
  mongo-data: