spring:
  application:
    name: bankonboarding
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/bankonboarding}
  docker:
    compose:
      file: compose-db.yaml
      lifecycle-management: start_and_stop

dadata:
  api:
    url: https://suggestions.dadata.ru/suggestions/api/4_1
    token: ${DADATA_API_KEY}